
import React from 'react';
import type { Crop } from './types';
import { Language } from './types';
import { LeafIcon } from './components/icons/LeafIcon';

export const CROPS: Crop[] = [
  { id: 'cotton', name: 'Cotton', icon: <LeafIcon className="w-8 h-8 text-green-700" /> },
  { id: 'wheat', name: 'Wheat', icon: <LeafIcon className="w-8 h-8 text-yellow-500" /> },
  { id: 'sugarcane', name: 'Sugarcane', icon: <LeafIcon className="w-8 h-8 text-lime-600" /> },
  { id: 'mango', name: 'Mango', icon: <LeafIcon className="w-8 h-8 text-orange-500" /> },
  { id: 'rice', name: 'Rice', icon: <LeafIcon className="w-8 h-8 text-blue-400" /> },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  [Language.EN]: {
    appName: "AgriAide",
    history: "History",
    about: "About",
    scanNewLeaf: "Scan New Leaf",
    scanLeaf: "Scan Leaf",
    selectCrop: "Select Crop",
    uploadInstruction: "Place the leaf in the center of the frame.",
    takePhoto: "Take Photo",
    uploadFromGallery: "Upload from Gallery",
    cameraGuidance: "Camera Guidance",
    cameraTip1: "Hold camera 15-20cm away from the leaf.",
    cameraTip2: "Ensure good lighting and avoid shadows.",
    cameraTip3: "Keep the leaf flat and in sharp focus.",
    analyzing: "Analyzing...",
    analysisMessage1: "Our AI is examining the leaf.",
    analysisMessage2: "This may take a moment...",
    analysisMessage3: "Checking for thousands of known diseases.",
    analysisResults: "Analysis Results",
    backToHome: "Back to Home",
    confidence: "Confidence",
    healthy: "Healthy",
    diseaseInfo: "Disease Information",
    symptoms: "Symptoms",
    remedies: "Remedies",
    chemical: "Chemical",
    organic: "Organic",
    prevention: "Prevention",
    scanHistory: "Scan History",
    noHistory: "No past scans found.",
    viewDetails: "View Details",
    error: "Error",
    errorGeneral: "An unknown error occurred.",
    errorAnalysis: "Could not analyze the image. Please try again with a clearer picture.",
    errorApiKey: "API key is not configured. Please contact support.",
    errorNoImage: "Please select an image first.",
    errorCameraPermission: "Camera access was denied. Please enable camera permissions in your browser settings to take a photo.",
    readAloud: "Read Aloud",
    stopReading: "Stop Reading",
    shareResults: "Share Results",
    copiedToClipboard: "Results copied to clipboard!",
    errorTTS: "Audio playback failed. Please check your internet connection or try reading the text below.",
    errorShare: "Sharing failed. You can try copying the text manually from the result cards.",
    dismiss: "Dismiss",
    errorCropMismatch: "The uploaded image does not appear to match the selected crop category. Please verify your selection and try again.",
    aboutTitle: "About AgriAide",
    missionTitle: "Our Mission",
    missionText: "To empower global agricultural communities with instant, accessible, and high-precision diagnostic tools, ensuring sustainable farming practices and food security through artificial intelligence.",
    q1: "Technology & Innovation",
    a1: "AgriAide is a state-of-the-art Progressive Web App (PWA) engineered with React and TypeScript. Our diagnostic engine utilizes the Google Gemini API, a frontier-model vision system capable of identifying subtle pathological patterns in crop foliage with expert-level precision.",
    q2: "Methodology",
    a2: "Upon image submission, our AI performs a multi-stage visual inspection, cross-referencing leaf morphology and lesions against a vast database of botanical diseases. The system provides localized advice on organic and chemical treatments, synchronized with the user's regional metadata.",
    q3: "Global Accessibility",
    a3: "We believe professional agricultural advice should be universal. AgriAide is fully localized in five regional languages—English, Urdu, Sindhi, Pashto, and Balochi—ensuring that linguistic barriers do not impede critical farming decisions.",
    q4: "Professional Disclaimer",
    a4: "While AgriAide provides highly accurate AI-driven diagnostics, it is intended as a supporting tool. Users are strongly advised to consult with certified local agronomists or agricultural extension services before initiating significant chemical interventions or large-scale crop treatments.",
    talkToExpert: "Talk to Expert",
    chatPlaceholder: "Ask follow-up questions...",
    chatWelcome: "I am your AI Agronomist. Ask me anything about this diagnosis!",
    sending: "Sending...",
  },
  [Language.UR]: {
    appName: "ایگری ایڈ",
    history: "ہسٹری",
    about: "معلومات",
    scanNewLeaf: "نئے پتے کو اسکین کریں",
    scanLeaf: "پتے کو اسکین کریں",
    selectCrop: "فصل منتخب کریں",
    uploadInstruction: "پتے کو فریم کے بیچ میں رکھیں۔",
    takePhoto: "تصویر لیں",
    uploadFromGallery: "گیلری سے اپ لوڈ کریں",
    cameraGuidance: "کیمرہ گائیڈنس",
    cameraTip1: "کیمرہ پتے سے 15-20 سینٹی میٹر دور رکھیں۔",
    cameraTip2: "اچھی روشنی کو یقینی بنائیں اور سائے سے بچیں۔",
    cameraTip3: "پتے کو ہموار رکھیں اور فوکس صاف رکھیں۔",
    analyzing: "تجزیہ کیا جا رہا ہے...",
    analysisMessage1: "ہمارا AI پتے کا معائنہ کر رہا ہے۔",
    analysisMessage2: "اس میں کچھ وقت لگ سکتا ہے...",
    analysisMessage3: "ہزاروں معلوم بیماریوں کی جانچ کی جا رہی ہے۔",
    analysisResults: "تجزیہ کے نتائج",
    backToHome: "ہوم پر واپس جائیں",
    confidence: "اعتماد",
    healthy: "صحت مند",
    diseaseInfo: "بیماری کی معلومات",
    symptoms: "علامات",
    remedies: "علاج",
    chemical: "کیمیائی",
    organic: "نامیاتی",
    prevention: "روک تھام",
    scanHistory: "اسکین ہسٹری",
    noHistory: "کوئی ماضی کے اسکین نہیں ملے۔",
    viewDetails: "تفصیلات دیکھیں",
    error: "خرابی",
    errorGeneral: "ایک نامعلوم خرابی واقع ہوئی ہے۔",
    errorAnalysis: "تصویر کا تجزیہ نہیں کیا جا سکا۔ براہ کرم ایک صاف تصویر کے ساتھ دوبارہ کوشش کریں۔",
    errorApiKey: "API کلید تشکیل نہیں دی گئی ہے۔ براہ کرم سپورٹ سے رابطہ کریں۔",
    errorNoImage: "براہ کرم پہلے ایک تصویر منتخب کریں۔",
    errorCameraPermission: "کیمرے تک رسائی مسترد کر دی گئی۔ براہ کرم تصویر لینے کے لیے اپنے براؤزر کی ترتیبات میں کیمرے کی اجازت دیں اور دوبارہ کوشش کریں۔",
    readAloud: "بلند آواز میں پڑھیں",
    stopReading: "پڑھنا بند کریں",
    shareResults: "نتائج شیئر کریں",
    copiedToClipboard: "نتائج کلپ بورڈ پر کاپی ہو گئے۔",
    errorTTS: "آڈیو پلے بیک ناکام ہو گیا۔ براہ کرم اپنا انٹرنیٹ کنکشن چیک کریں یا نیچے دی گئی تحریر پڑھیں۔",
    errorShare: "شیئرنگ ناکام ہو گئی۔ آپ نتائج کے کارڈز سے دستی طور پر متن کاپی کرنے کی کوشش کر سکتے ہیں۔",
    dismiss: "ختم کریں",
    errorCropMismatch: "اپ لوڈ کی گئی تصویر منتخب کردہ فصل کے زمرے سے مماثلت نہیں رکھتی۔ براہ کرم اپنے انتخاب کی تصدیق کریں اور دوبارہ کوشش کریں۔",
    aboutTitle: "ایگری ایڈ کے بارے میں",
    missionTitle: "ہمارا مشن",
    missionText: "مصنوعی ذہانت کے ذریعے عالمی زرعی کمیونٹیز کو فوری، قابل رسائی اور اعلیٰ درستگی کے تشخیصی ٹولز کے ساتھ بااختیار بنانا، پائیدار کاشتکاری کے طریقوں اور غذائی تحفظ کو یقینی بنانا۔",
    q1: "ٹیکنالوجی اور جدت",
    a1: "ایگری ایڈ ایک جدید پروگریسو ویب ایپ (PWA) ہے جسے React اور TypeScript کے ساتھ بنایا گیا ہے۔ ہمارا تشخیصی انجن گوگل جیمنی API کا استعمال کرتا ہے، جو ایک جدید ویژن سسٹم ہے جو پتوں میں بیماریوں کے باریک نمونوں کی ماہرانہ درستگی کے ساتھ شناخت کرنے کی صلاحیت رکھتا ہے۔",
    q2: "طریقہ کار",
    a2: "تصویر جمع کرانے پر، ہمارا AI کثیر مرحلہ وار معائنہ کرتا ہے، اور پتوں کی ساخت اور زخموں کا موازنہ بیماریوں کے ایک وسیع ڈیٹا بیس سے کرتا ہے۔ یہ نظام نامیاتی اور کیمیائی علاج پر مقامی مشورہ فراہم کرتا ہے۔",
    q3: "عالمی رسائی",
    a3: "ہمارا ماننا ہے کہ پیشہ ورانہ زرعی مشورہ سب کے لیے ہونا چاہیے۔ ایگری ایڈ پانچ علاقائی زبانوں—انگریزی، اردو، سندھی، پشتو اور بلوچی میں مکمل طور پر دستیاب ہے تاکہ لسانی رکاوٹیں کاشتکاری کے فیصلوں میں رکاوٹ نہ بنیں۔",
    q4: "پیشہ ورانہ انتباہ",
    a4: "اگرچہ ایگری ایڈ انتہائی درست تشخیص فراہم کرتا ہے، لیکن یہ ایک معاون آلے کے طور پر تیار کیا گیا ہے۔ صارفین کو سختی سے مشورہ دیا جاتا ہے کہ وہ کسی بھی کیمیائی مداخلت یا بڑے پیمانے پر علاج شروع کرنے سے پہلے مقامی زرعی ماہرین سے مشورہ کریں۔",
    talkToExpert: "ماهر سے بات کریں",
    chatPlaceholder: "مزید سوالات پوچھیں...",
    chatWelcome: "میں آپ کا AI ماہرِ زراعت ہوں۔ اس تشخیص کے بارے میں مجھ سے کچھ بھی پوچھیں!",
    sending: "بھیجا جا رہا ہے...",
  },
  [Language.SI]: {
    appName: "زرعي مددگار",
    history: "تاريخ",
    about: "بابت",
    scanNewLeaf: "نئين پن کي اسڪين ڪريو",
    scanLeaf: "پن کي اسڪين ڪريو",
    selectCrop: "فصل چونڊيو",
    uploadInstruction: "پن کي فريم جي وچ ۾ رکو.",
    takePhoto: "تصوير ڪڍو",
    uploadFromGallery: "گيلري مان اپلوڊ ڪريو",
    cameraGuidance: "ڪيمرا جي ھدايت",
    cameraTip1: "ڪيمرا پن کان 15-20 سينٽي ميٽر پري رکو.",
    cameraTip2: "بهترين روشني کي يقيني بڻايو ۽ پاڇي کان بچو.",
    cameraTip3: "پن کي سنئون رکو ۽ فوڪس صاف رکو.",
    analyzing: "تجربو ڪيو پيو وڃي...",
    analysisMessage1: "اسان جو AI پن جو معائنو ڪري رهيو آهي.",
    analysisMessage2: "هن ۾ ڪجهه وقت لڳي سگهي ٿو...",
    analysisMessage3: "هزارين سڃاتل بيمارين جي چڪاس ڪئي پئي وڃي.",
    analysisResults: "تجزيي جا نتيجا",
    backToHome: "گهر ڏانهن واپس وڃو",
    confidence: "اعتماد",
    healthy: "صحتمند",
    diseaseInfo: "بيماري جي معلومات",
    symptoms: "علامتون",
    remedies: "علاج",
    chemical: "ڪيميائي",
    organic: "نامياتي",
    prevention: "روڪٿام",
    scanHistory: "اسڪين جي تاريخ",
    noHistory: "ڪو به ماضي اسڪين نه مليو.",
    viewDetails: "تفصيل ڏسو",
    error: "نقص",
    errorGeneral: "هڪ اڻڄاتل نقص ٿيو.",
    errorAnalysis: "تصوير جو تجزيو نه ٿي سگهيو. مهرباني ڪري هڪ صاف تصوير سان ٻيهر ڪوشش ڪريو.",
    errorApiKey: "API چاٻي ترتيب نه ڏني وئي آهي. مهرباني ڪري مدد سان رابطو ڪريو.",
    errorNoImage: "مهرباني ڪري پهرين هڪ تصوير چونڊيو.",
    errorCameraPermission: "ڪيمرا جي رسائي رد ڪئي وئي. مهرباني ڪري برائوزر سيٽنگن ۾ ڪيمرا جي اجازت ڏيو.",
    readAloud: "زور سان پڙھو",
    stopReading: "پڙهڻ بند ڪريو",
    shareResults: "نتيجي کي شيئر ڪريو",
    copiedToClipboard: "نتيجا ڪلپ بورڊ تي ڪاپي ٿي ويا!",
    errorTTS: "آڊيو پلي بيڪ ناڪام ٿي ويو. مهرباني ڪري پنهنجو انٽرنيٽ ڪنيڪشن چيڪ ڪريو يا هيٺ ڏنل تحرير پڙهو.",
    errorShare: "شيئرنگ ناڪام ٿي وئي. توهان نتيجن جي ڪارڊن تان دستي طور متن ڪاپي ڪرڻ جي ڪوشش ڪري سگهو ٿا.",
    dismiss: "خارج ڪريو",
    errorCropMismatch: "اپ لوڊ ڪيل تصوير چونڊيل فصل سان ميل نه ٿي کائي. مهرباني ڪري پنهنجي چونڊ جي تصديق ڪريو ۽ ٻيهر ڪوشش ڪريو.",
    aboutTitle: "زرعي مددگار بابت",
    missionTitle: "اسان جو مقصد",
    missionText: "مصنوعي ذهانت جي ذريعي عالمي زرعي برادرين کي فوري ۽ اعليٰ درستگي جي تشخيصي اوزارن سان بااختيار بنائڻ، پائيدار پوک ۽ غذائي تحفظ کي يقيني بڻائڻ.",
    q1: "ٽيڪنالاجي ۽ جدت",
    a1: "زرعي مددگار هڪ جديد پروگريسيو ويب ايپ (PWA) آهي جيڪا React ۽ TypeScript سان ٺهيل آهي. اسان جو تشخيصي انجڻ گوگل جيمينائي API جو استعمال ڪري ٿو، جيڪو پنن ۾ بيمارين جي سڃاڻپ لاءِ هڪ جديد نظام آهي.",
    q2: "طريقو",
    a2: "تصوير جمع ڪرائڻ تي، اسان جو AI هڪ گھڻ-مرحلي معائنو ڪري ٿو، ۽ پنن جي ساخت جو مقابلو بيمارين جي هڪ وڏي ڊيٽابيس سان ڪري ٿو. هي نظام نامياتي ۽ ڪيميائي علاج تي مشورو ڏئي ٿو.",
    q3: "عالمي پهچ",
    a3: "اسان جو مڃڻ آهي ته زرعي مشورو سڀني لاءِ هجڻ گهرجي. زرعي مددگار پنجن علائقائي ٻولين—انگريزي، اردو، سنڌي، پشتو ۽ بلوچي ۾ موجود آهي ته جيئن ٻولي رڪاوٽ نه بڻجي.",
    q4: "پيشه ورانه خبرداري",
    a4: "جيتوڻيڪ زرعي مددگار اعليٰ درستگي مهيا ڪري ٿو، پر هي هڪ مددگار اوزار آهي. صارفين کي صلاح ڏجي ٿي ته ڪنهن به علاج شروع ڪرڻ کان اڳ مقامي زرعي ماهرن سان مشورو ڪن.",
    talkToExpert: "ماهر سان ڳالهايو",
    chatPlaceholder: "وڌيڪ سوال پڇو...",
    chatWelcome: "مان توهان جو AI زرعي ماهر آهيان. هن تشخيص بابت مون کان ڪجهه به پڇو!",
    sending: "موڪليو پيو وڃي...",
  },
  [Language.PS]: {
    appName: "اګري ایډ",
    history: "تاریخچه",
    about: "په اړه",
    scanNewLeaf: "نوې پاڼه سکین کړئ",
    scanLeaf: "پاڼه سکین کړئ",
    selectCrop: "فصل وټاکئ",
    uploadInstruction: "پاڼه د فریم په منځ کې کیږدئ.",
    takePhoto: "عکس واخلئ",
    uploadFromGallery: "له ګالري څخه پورته کړئ",
    cameraGuidance: "د کامرې لارښود",
    cameraTip1: "کمره له پاڼې څخه 15-20 سانتي متره لرې ونیسئ.",
    cameraTip2: "ښه رڼا یقیني کړئ او له سیوري څخه ځان وساتئ.",
    cameraTip3: "پاڼه هواره وساتئ او فوکس صاف کړئ.",
    analyzing: "تحلیل کیږي...",
    analysisMessage1: "زموږ AI پاڼه معاینه کوي.",
    analysisMessage2: "دا ممکن یو څه وخت ونیسي...",
    analysisMessage3: "د زرګونو پیژندل شویو ناروغیو لپاره کتل کیږي.",
    analysisResults: "د تحلیل پایلې",
    backToHome: "کور ته ستنیدل",
    confidence: "باور",
    healthy: "روغ",
    diseaseInfo: "د ناروغۍ معلومات",
    symptoms: "نښې نښانې",
    remedies: "درملنه",
    chemical: "کیمیاوي",
    organic: "عضوي",
    prevention: "مخنیوی",
    scanHistory: "د سکین تاریخچه",
    noHistory: "هیڅ پخوانی سکین ونه موندل شو.",
    viewDetails: "تفصیلات وګورئ",
    error: "خطا",
    errorGeneral: "یوه نامعلومه خطا رامنځته شوه.",
    errorAnalysis: "د انځور تحلیل ممکن نه و. مهرباني وکړئ په یوه روښانه انځور سره بیا هڅه وکړئ.",
    errorApiKey: "API کیلي نه ده تنظیم شوې. مهرباني وکړئ له ملاتړ سره اړیکه ونیسئ.",
    errorNoImage: "مهرباني وکړئ لومړی یو انځور وټاکئ.",
    errorCameraPermission: "کامرې ته لاسرسی رد شو. مهرباني وکړئ د کامرې اجازه ورکړئ.",
    readAloud: "په لوړ غږ ولولئ",
    stopReading: "لوستل ودروئ",
    shareResults: "پایلې شریک کړئ",
    copiedToClipboard: "پایلې کلپ بورډ ته کاپي شوې!",
    errorTTS: "د آډیو پلې بیک ناکام شو. مهرباني وکړئ خپل انټرنیټ اتصال وګورئ یا لاندې متن ولولئ.",
    errorShare: "شریکول ناکام شول. تاسو کولی شئ په لاسي ډول د پایلې کارتونو څخه متن کاپي کړئ.",
    dismiss: "رد کول",
    errorCropMismatch: "اپلوډ شوی عکس د غوره شوي فصل سره مطابقت نلري. مهرباني وکړئ خپل انتخاب تایید کړئ او بیا هڅه وکړئ.",
    aboutTitle: "د اګري ایډ په اړه",
    missionTitle: "زموږ ماموریت",
    missionText: "د مصنوعي ذهانت له لارې د نړیوالو زراعتي ټولنو ځواکمنول، د دقیق تشخیصي وسیلو له لارې د دوامداره کرنې او غذایي خوندیتوب تضمین کول.",
    q1: "ټیکنالوژي او نوښت",
    a1: "اګري ایډ یو عصري پروګریسیو ویب ایپ (PWA) دی چې په React او TypeScript کې جوړ شوی. زموږ تشخیصي ماشین د ګوګل جیمني API کاروي، کوم چې د ناروغیو په پیژندلو کې خورا لوړه دقت لري.",
    q2: "طریقه",
    a2: "د انځور په سپارلو سره، زموږ AI د پاڼو معاینه کوي او د ناروغیو له یو لوی ډیټابیس سره یې پرتله کوي. دا سیسټم د عضوي او کیمیاوي درملنې په اړه مشورې ورکوي.",
    q3: "نړیوال لاسرسی",
    a3: "زموږ باور دا دی چې زراعتي مشوره باید ټولو ته ورسیږي. اګري ایډ په پنځو سیمه ایزو ژبو—انګلیسي، اردو، سندهي، پښتو او بلوچي کې شتون لري.",
    q4: "مسلکي خبرتیا",
    a4: "که څه هم اګري ایډ دقیق تشخیص کوي، خو دا یوه مرستندویه وسیله ده. کاروونکو ته مشوره ورکول کیږي چې د هر ډول درملنې پیل کولو دمخه له متخصصینو سره مشوره وکړي.",
    talkToExpert: "له متخصص سره خبرې وکړئ",
    chatPlaceholder: "نورې پوښتنې وکړئ...",
    chatWelcome: "زه ستاسو د AI کرنې متخصص یم. د دې تشخیص په اړه له ما څخه هر څه وپوښتئ!",
    sending: "لیږل کیږي...",
  },
  [Language.BAL]: {
    appName: "اگری ایڈ",
    history: "تاریخ",
    about: "باروا",
    scanNewLeaf: "نوکیں پَن ءَ اسکین کن",
    scanLeaf: "پَن ءَ اسکین کن",
    selectCrop: "فصل ءَ گِچین کن",
    uploadInstruction: "پَن ءَ فریم ءِ نیام ءَ ایر کن۔",
    takePhoto: "عکس ءَ بگر",
    uploadFromGallery: "گەلری ءَ چہ اپلوڈ کن",
    cameraGuidance: "کیمرہ ءِ رھبند",
    cameraTip1: "کیمرہ ءَ پَن ءَ چہ 15-20 سینٹی میٹر دور بدار۔",
    cameraTip2: "روژنائی ءِ المی ءَ بکن ءُ چہ ساہگ ءَ بہ رک۔",
    cameraTip3: "پَن ءَ تچک بدار ءُ فوکس ءَ صاف بکن۔",
    analyzing: "تجزیہ کنگ بیت...",
    analysisMessage1: "مئے AI پَن ءِ معائنہ کنگ ءَ انت۔",
    analysisMessage2: "اے کار ءَ کمیں وخت لگیت...",
    analysisMessage3: "ہزاراں زانگ بیتگیں نادراہیانی چارگ بیت۔",
    analysisResults: "تجزیہ ءِ نتیجہ",
    backToHome: "گِس ءَ پدی رو",
    confidence: "باور",
    healthy: "صحت مند",
    diseaseInfo: "نادراہی ءِ معلومات",
    symptoms: "نشانی",
    remedies: "علاج",
    chemical: "کیمیائی",
    organic: "نامیاتی",
    prevention: "روک تھام",
    scanHistory: "اسکین تاریخ",
    noHistory: "هچ پیسری اسکین دست نہ کپت۔",
    viewDetails: "تفصیلات ءَ بچار",
    error: "خرابی",
    errorGeneral: "یک نامعلومیں خرابی ءَ پیش آتکگ۔",
    errorAnalysis: "عکس ءِ تجزیہ نہ بیت۔ مہربانی کن یک صافیں عکس ءَ گوں پدا جہد کن۔",
    errorApiKey: "API کی کلید ترتیب کنگ نہ بیت۔ مہربانی کن سپورٹ ءَ گوں رابطہ کن۔",
    errorNoImage: "مہربانی کن اول یک عکس ءَ گچین کن۔",
    errorCameraPermission: "کیمرہ ءِ رسائی نہ بوت. مہربانی کن کیمرہ ءِ اجازت ءَ بکن.",
    readAloud: "گوں توار ءَ بوان",
    stopReading: "وانگ ءَ بند کن",
    shareResults: "نتائج ءَ شیئر کن",
    copiedToClipboard: "نتیجہ کلپ بورڈ ءَ کاپی بیتگ انت!",
    errorTTS: "آڈیو پلے بیک ناکام بوت۔ مہربانی کن وتی انٹرنیٹ کنکشن ءَ بچار یا اے متن ءَ بوان۔",
    errorShare: "شیئرنگ ناکام بوت۔ تو وتی جند ءَ کارڈز ءَ چہ متن ءَ کاپی کت کن ئے.",
    dismiss: "بند کن",
    errorCropMismatch: "اپلوڈ کتگیں عکس منتخب کتگیں فصل ءِ زمرہ ءَ گوں ھمگرنچ نہ انت۔ مہربانی کن وتی گچین کاری ءِ پجاری ءَ بکن ءُ پدا جہد کن۔",
    aboutTitle: "اگری ایڈ ءِ باروا",
    missionTitle: "مئے مقصد",
    missionText: "مصنوعی ذہانت ءِ کمک ءَ مچی زرعی برادری ءَ را زوت ءُ درستیں تشخیصی اوزاراں گوں بااختیار جوڑ کنگ، پائیدار کشت ءُ کشاری ءُ وراک ءِ حفاظت ءَ المی کنگ۔",
    q1: "ٹیکنالوجی ءُ نوک سازی",
    a1: "اگری ایڈ یک نوکیں ویب ایپ (PWA) ے کہ React ءُ TypeScript ءِ سرا جوڑ انت۔ مئے انجن گوگل جیمینائی API کارمرز کنت، کہ آ پناں نادراہیانی پجارگ ءَ باز زانتکار انت۔",
    q2: "طریقہ کار",
    a2: "عکس ءَ دیم دیگ ءَ پد، مئے AI پَنانی بچار ءَ کنت ءُ نادراہیانی ڈیٹا بیس ءَ گوں توازن کنت۔ اے نظام علاج ءِ باروا صلاح دنت۔",
    q3: "عالمی رسائی",
    a3: "ما باور کنیں کہ زرعی مشورہ درستاں الم دست بہ کپیت۔ اگری ایڈ پنچ علاقائی زباناں—انگریزی، اردو، سندھی، پشتو ءُ بلوچی ءَ موجود انت۔",
    q4: "پیشہ ورانہ انتباہ",
    a4: "اگری ایڈ درستیں تشخیص کنت، بلے اے یک کمک کنوکیں اوزارے۔ علاج ءَ چہ پیسر وتی مقامی زرعی ماہر ءَ گوں مشورہ الم بکن ات۔",
    talkToExpert: "ماهر ءَ گوں گپ بکن",
    chatPlaceholder: "پدا جست بکن...",
    chatWelcome: "من تئی AI زراعت ءِ ماهر آں۔ اے تشخیص ءِ باروا چہ من هرچیے جست بکن!",
    sending: "دیم دیگ بیت...",
  },
};
