
import React from 'react';
import type { Crop } from './types';
import { Language } from './types';
import { LeafIcon } from './components/icons/LeafIcon';

export const CROPS: Crop[] = [
  { id: 'cotton', name: 'Cotton', icon: <LeafIcon className="w-8 h-8 text-green-700" /> },
  { id: 'wheat', name: 'Wheat', icon: <LeafIcon className="w-8 h-8 text-yellow-500" /> },
  { id: 'sugarcane', name: 'Sugarcane', icon: <LeafIcon className="w-8 h-8 text-lime-600" /> },
  { id: 'mango', name: 'Mango', icon: <LeafIcon className="w-8 h-8 text-orange-500" /> },
  { id: 'rice', name: 'Rice', icon: <LeafIcon className="w-8 h-8 text-blue-400" /> },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  [Language.EN]: {
    appName: "AgriAide",
    history: "History",
    about: "About",
    scanNewLeaf: "Scan New Leaf",
    scanLeaf: "Scan Leaf",
    selectCrop: "Select Crop",
    uploadInstruction: "Place the leaf in the center of the frame.",
    takePhoto: "Take Photo",
    uploadFromGallery: "Upload from Gallery",
    analyzing: "Analyzing...",
    analysisMessage1: "Our AI is examining the leaf.",
    analysisMessage2: "This may take a moment...",
    analysisMessage3: "Checking for thousands of known diseases.",
    analysisResults: "Analysis Results",
    backToHome: "Back to Home",
    confidence: "Confidence",
    healthy: "Healthy",
    diseaseInfo: "Disease Information",
    symptoms: "Symptoms",
    remedies: "Remedies",
    chemical: "Chemical",
    organic: "Organic",
    prevention: "Prevention",
    scanHistory: "Scan History",
    noHistory: "No past scans found.",
    viewDetails: "View Details",
    error: "Error",
    errorGeneral: "An unknown error occurred.",
    errorAnalysis: "Could not analyze the image. Please try again with a clearer picture.",
    errorApiKey: "API key is not configured. Please contact support.",
    errorNoImage: "Please select an image first.",
    readAloud: "Read Aloud",
    stopReading: "Stop Reading",
    shareResults: "Share Results",
    copiedToClipboard: "Results copied to clipboard!",
    errorTTS: "Audio playback failed. Please check your internet connection or try reading the text below.",
    errorShare: "Sharing failed. You can try copying the text manually from the result cards.",
    dismiss: "Dismiss",
    errorCropMismatch: "The uploaded image does not appear to match the selected crop category. Please verify your selection and try again.",
    aboutTitle: "About AgriAide",
    q1: "What technology is used in this project?",
    a1: "This app is a Progressive Web App (PWA) built with React, TypeScript, and Tailwind CSS. The core analysis is powered by the Google Gemini API, which processes the leaf images to identify diseases.",
    q2: "How does this project work?",
    a2: "You select a crop, then upload a clear photo of a plant leaf. The app sends this image to the Gemini AI model, which analyzes it and returns a detailed diagnosis including the disease name, confidence score, symptoms, remedies, and prevention tips. All results are provided in your selected language.",
    q3: "Which languages are used to create this project?",
    a3: "The application itself is written in TypeScript using the React framework. The user interface is available in multiple languages: English, Urdu, Sindhi, Pashto, and Balochi.",
    q4: "What are its limitations?",
    a4: "The AI's accuracy depends heavily on the quality (clarity, lighting) of the uploaded photo. This tool provides an AI-generated suggestion and should not replace consultation with a professional agronomist. An internet connection is required for the analysis.",
  },
  [Language.UR]: {
    appName: "ایگری ایڈ",
    history: "ہسٹری",
    about: "معلومات",
    scanNewLeaf: "نئے پتے کو اسکین کریں",
    scanLeaf: "پتے کو اسکین کریں",
    selectCrop: "فصل منتخب کریں",
    uploadInstruction: "پتے کو فریم کے بیچ میں رکھیں۔",
    takePhoto: "تصویر لیں",
    uploadFromGallery: "گیلری سے اپ لوڈ کریں",
    analyzing: "تجزیہ کیا جا رہا ہے...",
    analysisMessage1: "ہمارا AI پتے کا معائنہ کر رہا ہے۔",
    analysisMessage2: "اس میں کچھ وقت لگ سکتا ہے...",
    analysisMessage3: "ہزاروں معلوم بیماریوں کی جانچ کی جا رہی ہے۔",
    analysisResults: "تجزیہ کے نتائج",
    backToHome: "ہوم پر واپس جائیں",
    confidence: "اعتماد",
    healthy: "صحت مند",
    diseaseInfo: "بیماری کی معلومات",
    symptoms: "علامات",
    remedies: "علاج",
    chemical: "کیمیائی",
    organic: "نامیاتی",
    prevention: "روک تھام",
    scanHistory: "اسکین ہسٹری",
    noHistory: "کوئی ماضی کے اسکین نہیں ملے۔",
    viewDetails: "تفصیلات دیکھیں",
    error: "خرابی",
    errorGeneral: "ایک نامعلوم خرابی واقع ہوئی ہے۔",
    errorAnalysis: "تصویر کا تجزیہ نہیں کیا جا سکا۔ براہ کرم ایک صاف تصویر کے ساتھ دوبارہ کوشش کریں۔",
    errorApiKey: "API کلید تشکیل نہیں دی گئی ہے۔ براہ کرم سپورٹ سے رابطہ کریں۔",
    errorNoImage: "براہ کرم پہلے ایک تصویر منتخب کریں۔",
    readAloud: "بلند آواز میں پڑھیں",
    stopReading: "پڑھنا بند کریں",
    shareResults: "نتائج شیئر کریں",
    copiedToClipboard: "نتائج کلپ بورڈ پر کاپی ہو گئے۔",
    errorTTS: "آڈیو پلے بیک ناکام ہو گیا۔ براہ کرم اپنا انٹرنیٹ کنکشن چیک کریں یا نیچے دی گئی تحریر پڑھیں۔",
    errorShare: "شیئرنگ ناکام ہو گئی۔ آپ نتائج کے کارڈز سے دستی طور پر متن کاپی کرنے کی کوشش کر سکتے ہیں۔",
    dismiss: "ختم کریں",
    errorCropMismatch: "اپ لوڈ کی گئی تصویر منتخب کردہ فصل کے زمرے سے مماثلت نہیں رکھتی۔ براہ کرم اپنے انتخاب کی تصدیق کریں اور دوبارہ کوشش کریں۔",
    aboutTitle: "ایگری ایڈ کے بارے میں",
    q1: "اس پروجیکٹ میں کون سی ٹیکنالوجی استعمال ہوتی ہے؟",
    a1: "یہ ایپ ایک پروگریسو ویب ایپ (PWA) ہے جو React، TypeScript، اور Tailwind CSS کے ساتھ بنائی گئی ہے۔ مرکزی تجزیہ گوگل جیمنی API کے ذریعے کیا جاتا ہے، جو بیماریوں کی شناخت کے لیے پتوں کی تصاویر پر کارروائی کرتا ہے۔",
    q2: "یہ پروجیکٹ کیسے کام کرتا ہے؟",
    a2: "آپ ایک فصل منتخب کرتے ہیں، پھر پودے کے پتے کی صاف تصویر اپ لوڈ کرتے ہیں۔ ایپ اس تصویر کو جیمنی AI ماڈل کو بھیجتی ہے، جو اس کا تجزیہ کرتا ہے اور بیماری کا نام، اعتماد کا اسکور، علامات، علاج اور روک تھام کے نکات سمیت تفصیلی تشخیص واپس کرتا ہے۔ تمام نتائج آپ کی منتخب کردہ زبان میں فراہم کیے جاتے ہیں۔",
    q3: "اس پروجیکٹ کو بنانے کے لیے کون سی زبانیں استعمال کی گئیں؟",
    a3: "ایپلی کیشن خود React فریم ورک کا استعمال کرتے ہوئے TypeScript میں لکھی گئی ہے۔ یوزر انٹرفیس متعدد زبانوں میں دستیاب ہے: انگریزی، اردو، سندھی، پشتو، اور بلوچی۔",
    q4: "اس کی حدود کیا ہیں؟",
    a4: "ای اے آئی کی درستگی کا انحصار اپ لوڈ کردہ تصویر کے معیار (صفائی، روشنی) پر ہوتا ہے۔ یہ ٹول AI سے تیار کردہ تجویز فراہم کرتا ہے اور اسے کسی پیشہ ور زرعی ماہر سے مشاورت کا متبادل نہیں سمجھا جانا چاہیے۔ تجزیہ کے لیے انٹرنیٹ کنکشن درکار ہے۔",
  },
  [Language.SI]: {
    appName: "زرعي مددگار",
    history: "تاريخ",
    about: "بابت",
    scanNewLeaf: "نئين پن کي اسڪين ڪريو",
    scanLeaf: "پن کي اسڪين ڪريو",
    selectCrop: "فصل چونڊيو",
    uploadInstruction: "پن کي فريم جي وچ ۾ رکو.",
    takePhoto: "تصوير ڪڍو",
    uploadFromGallery: "گيلري مان اپلوڊ ڪريو",
    analyzing: "تجربو ڪيو پيو وڃي...",
    analysisMessage1: "اسان جو AI پن جو معائنو ڪري رهيو آهي.",
    analysisMessage2: "هن ۾ ڪجهه وقت لڳي سگهي ٿو...",
    analysisMessage3: "هزارين سڃاتل بيمارين جي چڪاس ڪئي پئي وڃي.",
    analysisResults: "تجزيي جا نتيجا",
    backToHome: "گهر ڏانهن واپس وڃو",
    confidence: "اعتماد",
    healthy: "صحتمند",
    diseaseInfo: "بيماري جي معلومات",
    symptoms: "علامتون",
    remedies: "علاج",
    chemical: "ڪيميائي",
    organic: "نامياتي",
    prevention: "روڪٿام",
    scanHistory: "اسڪين جي تاريخ",
    noHistory: "ڪو به ماضي اسڪين نه مليو.",
    viewDetails: "تفصيل ڏسو",
    error: "نقص",
    errorGeneral: "هڪ اڻڄاتل نقص ٿيو.",
    errorAnalysis: "تصوير جو تجزيو نه ٿي سگهيو. مهرباني ڪري هڪ صاف تصوير سان ٻيهر ڪوشش ڪريو.",
    errorApiKey: "API چاٻي ترتيب نه ڏني وئي آهي. مهرباني ڪري مدد سان رابطو ڪريو.",
    errorNoImage: "مهرباني ڪري پهرين هڪ تصوير چونڊيو.",
    readAloud: "زور سان پڙھو",
    stopReading: "پڙهڻ بند ڪريو",
    shareResults: "نتيجي کي شيئر ڪريو",
    copiedToClipboard: "نتيجا ڪلپ بورڊ تي ڪاپي ٿي ويا!",
    errorTTS: "آڊيو پلي بيڪ ناڪام ٿي ويو. مهرباني ڪري پنهنجو انٽرنيٽ ڪنيڪشن چيڪ ڪريو يا هيٺ ڏنل تحرير پڙهو.",
    errorShare: "شيئرنگ ناڪام ٿي وئي. توهان نتيجن جي ڪارڊن تان دستي طور متن ڪاپي ڪرڻ جي ڪوشش ڪري سگهو ٿا.",
    dismiss: "خارج ڪريو",
    errorCropMismatch: "اپ لوڊ ڪيل تصوير چونڊيل فصل سان ميل نه ٿي کائي. مهرباني ڪري پنهنجي چونڊ جي تصديق ڪريو ۽ ٻيهر ڪوشش ڪريو.",
    aboutTitle: "زرعي مددگار بابت",
    q1: "هن منصوبي ۾ ڪهڙي تيڪنالاجي استعمال ٿيل آهي؟",
    a1: "هي ايپ هڪ پروگريسو ویب ايپ (PWA) آهي جيڪا React, TypeScript, ۽ Tailwind CSS سان ٺهيل آهي. بنيادي تجزيو گوگل جيمينائي API جي ذريعي ڪيو ويندو آهي, جيڪو پنن جي تصويرن کي بيمارين جي سڃاڻپ لاءِ پروسيس ڪري ٿو.",
    q2: "هن منصوبو ڪيئن ڪم ڪري ٿو؟",
    a2: "توهان هڪ فصل چونڊيندا آهيو, پوءِ ٻوٽي جي پن جي صاف تصوير اپلوڊ ڪندا آهيو. ايپ هي تصوير جيمينائي AI ماڊل ڏانهن موڪليندي آهي, جيڪو ان جو تجزيو ڪري ٿو اور تفصيلي تشخيص واپس ڪري ٿو جنهن ۾ بيماري جو نالو, اعتماد جو اسڪور, علامتون, علاج, ۽ بچاءَ جا طريقا شامل آهن. سڀ نتيجا توهان جي چونڊيل ٻوليءَ ۾ مهيا ڪيا ويندا آهن.",
    q3: "هن منصوبي کي ٺاهڻ لاءِ ڪهڙيون ٻوليون استعمال ڪيون ويون آهن؟",
    a3: "ايپليڪيشن پاڻ React فريم ورڪ استعمال ڪندي TypeScript ۾ لکيل آهي. يوزر انٽرفيس ڪيترن ئي ٻولين ۾ دستياب آهي: انگريزي, اردو, سنڌي, پشتو, ۽ بلوچي.",
    q4: "ان جون حدون ڪهڙيون آهن؟",
    a4: "AI جي درستگي اپلوڊ ڪيل تصوير جي معيار (صفائي, روشني) تي تمام گهڻو دارومدار رکي ٿي. هي اوزار AI پاران ٺاهيل تجويز فراهم ڪري ٿو ۽ ان کي پيشه ور زرعي ماهر سان صلاح مشوري جو متبادل نه سمجهڻ گهرجي. تجزيي لاءِ انٽرنيٽ ڪنيڪشن گهربل آهي.",
  },
  [Language.PS]: {
    appName: "اګري ایډ",
    history: "تاریخچه",
    about: "په اړه",
    scanNewLeaf: "نوې پاڼه سکین کړئ",
    scanLeaf: "پاڼه سکین کړئ",
    selectCrop: "فصل وټاکئ",
    uploadInstruction: "پاڼه د فریم په منځ کې کیږدئ.",
    takePhoto: "عکس واخلئ",
    uploadFromGallery: "له ګالري څخه پورته کړئ",
    analyzing: "تحلیل کیږي...",
    analysisMessage1: "زموږ AI پاڼه معاینه کوي.",
    analysisMessage2: "دا ممکن یو څه وخت ونیسي...",
    analysisMessage3: "د زرګونو پیژندل شویو ناروغیو لپاره کتل کیږي.",
    analysisResults: "د تحلیل پایلې",
    backToHome: "کور ته ستنیدل",
    confidence: "باور",
    healthy: "روغ",
    diseaseInfo: "د ناروغۍ معلومات",
    symptoms: "نښې نښانې",
    remedies: "درملنه",
    chemical: "کیمیاوي",
    organic: "عضوي",
    prevention: "مخنیوی",
    scanHistory: "د سکین تاریخچه",
    noHistory: "هیڅ پخوانی سکین ونه موندل شو.",
    viewDetails: "تفصیلات وګورئ",
    error: "خطا",
    errorGeneral: "یوه نامعلومه خطا رامنځته شوه.",
    errorAnalysis: "د انځور تحلیل ممکن نه و. مهرباني وکړئ په یوه روښانه انځور سره بیا هڅه وکړئ.",
    errorApiKey: "API کیلي نه ده تنظیم شوې. مهرباني وکړئ له ملاتړ سره اړیکه ونیسئ.",
    errorNoImage: "مهرباني وکړئ لومړی یو انځور وټاکئ.",
    readAloud: "په لوړ غږ ولولئ",
    stopReading: "لوستل ودروئ",
    shareResults: "پایلې شریک کړئ",
    copiedToClipboard: "پایلې کلپ بورډ ته کاپي شوې!",
    errorTTS: "د آډیو پلې بیک ناکام شو. مهرباني وکړئ خپل انټرنیټ اتصال وګورئ یا لاندې متن ولولئ.",
    errorShare: "شریکول ناکام شول. تاسو کولی شئ په لاسي ډول د پایلې کارتونو څخه متن کاپي کړئ.",
    dismiss: "رد کول",
    errorCropMismatch: "اپلوډ شوی عکس د غوره شوي فصل سره مطابقت نلري. مهرباني وکړئ خپل انتخاب تایید کړئ او بیا هڅه وکړئ.",
    aboutTitle: "د اګري ایډ په اړه",
    q1: "په دې پروژه کې کومه ټیکنالوژي کارول شوې؟",
    a1: "دا اپلیکیشن یو پرمختللی ویب اپلیکیشن (PWA) دی چې d React، TypeScript، او Tailwind CSS سره جوړ شوی. اصلي تحلیل د ګوګل جیمني API لخوا ترسره کیږي، کوم چې د ناروغیو پیژندلو لپاره د پاڼو انځورونه پروسس کوي.",
    q2: "دا پروژه څنګه کار کوي؟",
    a2: "تاسو یو فصل غوره کوئ، بیا د نبات د پاڼې یو روښانه عکس اپلوډ کوئ. اپلیکیشن دا انځور جیمني AI ماډل ته لیږي، کوم چې دا تحلیلوي او د ناروغۍ نوم، د باور نمرې، نښې نښانې، درملنې، او مخنیوي لارښوونو په شمول یو مفصل تشخیص بیرته راګرځوي. ټولې پایلې ستاسو په غوره شوې ژبه کې وړاندې کیږي.",
    q3: "د دې پروژې جوړولو لپاره کومې ژبې کارول شوي؟",
    a3: "اپلیکیشن پخپله د React چوکاټ په کارولو سره په TypeScript کې لیکل شوی. د کاروونکي انټرفیس په څو ژبو کې شتون لري: انګلیسي، اردو، سندهي، پښتو، او بلوچي.",
    q4: "د دې محدودیتونه څه دي؟",
    a4: "د AI دقت په لویه کچه د اپلوډ شوي عکس کیفیت (وضاحت، رڼا) پورې اړه لري. دا وسیله د AI لخوا تولید شوی وړاندیز وړاندې کوي او باید د مسلکي زراعت پوه سره د مشورې ځای ونیسي. د تحلیل لپاره انټرنیټ پیوستون اړین دی.",
  },
  [Language.BAL]: {
    appName: "اگری ایڈ",
    history: "تاریخ",
    about: "باروا",
    scanNewLeaf: "نوکیں پَن ءَ اسکین کن",
    scanLeaf: "پَن ءَ اسکین کن",
    selectCrop: "فصل ءَ گِچین کن",
    uploadInstruction: "پَن ءَ فریم ءِ نیام ءَ ایر کن۔",
    takePhoto: "عکس ءَ بگر",
    uploadFromGallery: "گەلری ءَ چہ اپلوڈ کن",
    analyzing: "تجزیہ کنگ بیت...",
    analysisMessage1: "مئے AI پَن ءِ معائنہ کنگ ءَ انت۔",
    analysisMessage2: "اے کار ءَ کمیں وخت لگیت...",
    analysisMessage3: "ہزاراں زانگ بیتگیں نادراہیانی چارگ بیت۔",
    analysisResults: "تجزیہ ءِ نتیجہ",
    backToHome: "گِس ءَ پدی رو",
    confidence: "باور",
    healthy: "صحت مند",
    diseaseInfo: "نادراہی ءِ معلومات",
    symptoms: "نشانی",
    remedies: "علاج",
    chemical: "کیمیائی",
    organic: "نامیاتی",
    prevention: "روک تھام",
    scanHistory: "اسکین تاریخ",
    noHistory: "هچ پیسری اسکین دست نہ کپت۔",
    viewDetails: "تفصیلات ءَ بچار",
    error: "خرابی",
    errorGeneral: "یک نامعلومیں خرابی ءَ پیش آتکگ۔",
    errorAnalysis: "عکس ءِ تجزیہ نہ بیت۔ مہربانی کن یک صافیں عکس ءَ گوں پدا جہد کن۔",
    errorApiKey: "API کی کلید ترتیب کنگ نہ بیت۔ مہربانی کن سپورٹ ءَ گوں رابطہ کن۔",
    errorNoImage: "مہربانی کن اول یک عکس ءَ گچین کن۔",
    readAloud: "گوں توار ءَ بوان",
    stopReading: "وانگ ءَ بند کن",
    shareResults: "نتائج ءَ شیئر کن",
    copiedToClipboard: "نتیجہ کلپ بورڈ ءَ کاپی بیتگ انت!",
    errorTTS: "آڈیو پلے بیک ناکام بوت۔ مہربانی کن وتی انٹرنیٹ کنکشن ءَ بچار یا اے متن ءَ بوان۔",
    errorShare: "شیئرنگ ناکام بوت۔ تو وتی جند ءَ کارڈز ءَ چہ متن ءَ کاپی کت کن ئے۔",
    dismiss: "بند کن",
    errorCropMismatch: "اپلوڈ کتگیں عکس منتخب کتگیں فصل ءِ زمرہ ءَ گوں ھمگرنچ نہ انت۔ مہربانی کن وتی گچین کاری ءِ پجاری ءَ بکن ءُ پدا جہد کن۔",
    aboutTitle: "اگری ایڈ ءِ باروا",
    q1: "اے پروجیکٹ ءَ چے ٹیکنالوجی کارمرز بیتگ؟",
    a1: "اے ایپ یک پروگریسو ویب ایپ (PWA) ے کہ گوں ری ایکٹ، ٹائپ اسکرپٹ، ءُ ٹیلونڈ سی ایس ایس ءَ جوڑ کنگ بیتگ۔ اصل تجزیہ گوگل جیمنی اے پی آئی ءِ ذریعہ کنگ بیت، کہ آ نادراہیانی پجارگ ءِ ھاتر ءَ پَنانی عکس آنی سرا کار کنت۔",
    q2: "اے پروجیکٹ چون کار کنت؟",
    a2: "تو یک فصلے گچین کن ئے، پدا یک پلانٹ ءِ پَن ءِ صافیں عکسے اپلوڈ کن ئے۔ ایپ اے عکس ءَ جیمنی اے آئی ماڈل ءَ دیم دنت، کہ آ ایشی ءِ تجزیہ کنت ءُ یک تفصیلی تشخیصے پدی دنت کہ آئی تہ ءَ نادراہی ءِ نام، باور ءِ اسکور، نشانی، علاج، ءُ رکگ ءِ صلاح ھوار انت۔ درست نتیجہ تئی گچین کتگیں زبان ءَ دیگ بنت۔",
    q3: "اے پروجیکٹ ءِ جوڑ کنگ ءَ چے زبان کارمرز کنگ بیتگ؟",
    a3: "ایپلیکیشن وت ری ایکٹ فریم ورک ءِ کارمرز کنگ ءَ گوں ٹائپ اسکرپٹ ءَ نبشتہ کنگ بیتگ۔ یوزر انٹرفیس بازیں زباناں دست کپیت: انگریزی، اردو، سندھی، پشتو، ءُ بلوچی۔",
    q4: "ایشی ءِ ھدود چی انت؟",
    a4: "اے آئی ءِ درستی اپلوڈ کتگیں عکس ءِ کوالٹی (صفائی، روژنائی) ءِ سرا باز دارگ بیت۔ اے ٹول یک اے آئی ءِ ذریعہ جوڑ کتگیں تجویزے پیش کنت ءُ ایشی ءَ یک پیشہ وریں زرعی زانتکارے ءِ مشورگ ءِ بدل نہ زانگ لوٹیت۔ تجزیہ ءِ ھاتر ءَ انٹرنیٹ کنکشن المی انت۔",
  },
};
